{{- if (not .Values.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mysql.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ template "mysql.name" . }}"
    chart: "{{ template "mysql.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  {{- if .Values.secret.annotations }}
  annotations: {{- include "mysql.tplValue" (dict "value" .Values.secret.annotations "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
{{- if .Values.secret.requirePasswords }}
data:
  mysql-database: "{{ .Values.db.name | b64enc }}"
  {{- if not (empty .Values.rootUser.password) }}
  mysql-root-password: "{{ .Values.rootUser.password | b64enc }}"
  {{- else if (not .Values.rootUser.forcePassword) }}
  mysql-root-password: "{{ randAlphaNum 10 | b64enc }}"
  {{ else }}
  mysql-root-password: {{ required "A MySQL Root Password is required!" .Values.rootUser.password }}
  {{- end }}
  {{- if not (empty .Values.db.password) }}
  mysql-password: "{{ .Values.db.password | b64enc }}"
  {{- else if (not .Values.db.forcePassword) }}
  mysql-password: "{{ randAlphaNum 10 | b64enc }}"
  {{- else }}
  mysql-password: {{ required "A MySQL Database Password is required!" .Values.db.password }}
  {{- end }}
  {{- if not (empty .Values.db.user) }}
  mysql-user: "{{ .Values.db.user | b64enc }}"
  {{- else if (not .Values.db.user) }}
  mysql-user: "{{ randAlphaNum 10 | b64enc }}"
  {{- else }}
  mysql-user: {{ required "A MySQL Database User is required!" .Values.db.user }}
  {{- end }}
{{- end }}
{{- end }}
