apiVersion: v1
kind: Service
metadata:
  name: {{ template "mysql.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ template "mysql.name" . }}"
    chart: "{{ template "mysql.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
{{- if .Values.db.service.annotations }}
{{ toYaml .Values.db.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "ClusterIP" }}
  {{- if .Values.service.clusterIp }}
  clusterIP: {{ .Values.service.clusterIp.master }}
  {{- end }}
  {{- end }}
  ports:
    - name: mysql
      port: {{ .Values.service.port }}
      targetPort: mysql
  {{- if eq .Values.service.type "NodePort" }}
  {{- if .Values.service.nodePort }}
  {{- if .Values.service.nodePort.master }}
      nodePort: {{ .Values.service.nodePort.master }}
  {{- end }}
  {{- end }}
  {{- end }}
  selector:
    app: "{{ template "mysql.name" . }}"
    release: "{{ .Release.Name }}"
